name: CI workflow # name 
on:  # triggers
  push:
      branches: [ "main" ]
  pull_request:
      branches: ["main"]
      
jobs: #jobs
  build:
    runs-on: ubuntu-latest #runner
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8  #verif standard code
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run unit tests with nose #color in tests
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
 
    
