name: CI workflow # name 
on:  # triggers
  push:
      branches: [ "main" ]
  pull_request:
      branches: ["main"]
      
jobs: #jobs
  build:
    runs-on: ubuntu-latest #runner
    container: python:3.9-slim
    
